services:
  # Content Validation Tests
  content-validation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ipc: host
    # Set exit-code-from to ensure Docker respects the exit code from the command
    command: >-
      sh -c "npx ts-node src/run-sharded-tests.ts content-validation"
    # Ensure container stops when the command exits
    restart: "no"

  # User Flows Tests
  user-flows:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ipc: host
    # Set exit-code-from to ensure Docker respects the exit code from the command
    command: >-
      sh -c "npx ts-node src/run-sharded-tests.ts user-flows"
    # Ensure container stops when the command exits
    restart: "no"

  # Interactions Tests
  interactions:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ipc: host
    # Set exit-code-from to ensure Docker respects the exit code from the command
    command: >-
      sh -c "npx ts-node src/run-sharded-tests.ts interactions"
    # Ensure container stops when the command exits
    restart: "no"
