services:
  # Content Validation Tests
  content-validation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ipc: host
    command: >-
      sh -c "npx ts-node src/run-sharded-tests.ts content-validation"
    restart: "no"

  # User Flows Tests
  user-flows:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ipc: host
    command: >-
      sh -c "npx ts-node src/run-sharded-tests.ts user-flows"
    restart: "no"

  # Interactions Tests
  interactions:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ipc: host
    command: >-
      sh -c "npx ts-node src/run-sharded-tests.ts interactions"
    restart: "no"
